[project]
name = "rlt2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "llama-cpp-python>=0.3.14",
    "tcod>=19.3.0",
]
